services:
  db:
    image: postgres:16
    container_name: parakeet_db
    env_file:
      - ./services/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: parakeet_api
    env_file:
      - ./api/.env
    environment:
      - DATABASE_HOST=db
    ports:
      - "3001:8000"
    depends_on:
      - db
    volumes:
      - ./api:/rails
      - bundle_data:/usr/local/bundle

volumes:
  postgres_data:
  bundle_data:
