FROM ruby:3.4.4

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      curl \
      postgresql-client \
      libpq-dev \
      libvips \
      nodejs \
      npm && \
    rm -rf /var/lib/apt/lists/*

COPY dev-start.sh /usr/local/bin/dev-start.sh
RUN chmod +x /usr/local/bin/dev-start.sh

CMD ["dev-start.sh"]
